// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-Wy6Nv7gUBgTcfMQjKFgHkvdb-_5589M',
    appId: '1:600120463845:web:fdd8d092bc6c6e08b81f0c',
    messagingSenderId: '600120463845',
    projectId: 'lease-c970e',
    authDomain: 'lease-c970e.firebaseapp.com',
    storageBucket: 'lease-c970e.appspot.com',
    measurementId: 'G-9JF7NVDGJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM-GSXwBrAIGCArHf3wMQBArEUmURnhi8',
    appId: '1:600120463845:android:7c4e8daf15168937b81f0c',
    messagingSenderId: '600120463845',
    projectId: 'lease-c970e',
    storageBucket: 'lease-c970e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9rhKfPHdE_3uBHRCraV91yuz0Dqn4zcc',
    appId: '1:600120463845:ios:f5dc6423bc709dcfb81f0c',
    messagingSenderId: '600120463845',
    projectId: 'lease-c970e',
    storageBucket: 'lease-c970e.appspot.com',
    iosBundleId: 'com.example.lease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9rhKfPHdE_3uBHRCraV91yuz0Dqn4zcc',
    appId: '1:600120463845:ios:9cf7fde701da45f7b81f0c',
    messagingSenderId: '600120463845',
    projectId: 'lease-c970e',
    storageBucket: 'lease-c970e.appspot.com',
    iosBundleId: 'com.example.lease.RunnerTests',
  );
}
